services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox
    ports: ["5432:5432"]
    volumes: ["reachinbox_pg:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes: ["reachinbox_redis:/data"]
volumes:
  reachinbox_pg:
  reachinbox_redis:
