import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, CalendarClock, Check, ChevronDown, Clock3, FileUp, Filter, LogOut, Mail, Paperclip, Plus, RefreshCw, Search, Send, Star, X } from 'lucide-react';
import { api, Email, User } from './api';
import './styles.css';

const formatDate = (value: string) => new Intl.DateTimeFormat('en-US', { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }).format(new Date(value));
const initials = (name: string) => name.split(' ').map(x => x[0]).slice(0,2).join('').toUpperCase();
function Avatar({ user, small = false }: { user: User; small?: boolean }) { const [imageFailed, setImageFailed] = useState(false); return <span className={`avatar${small ? ' small' : ''}`}>{user.avatar && !imageFailed ? <img src={user.avatar} referrerPolicy="no-referrer" onError={() => setImageFailed(true)} alt=""/> : initials(user.name)}</span>; }

function Login() { return <main className="login-page"><div className="window-bar">Login Screen</div><section className="login-card"><h1>Login</h1><button className="google-button" onClick={() => window.location.href = `${api.base}/api/auth/google`}><b>G</b> Login with Google</button><div className="divider"><span>or sign up through email</span></div><input placeholder="Email ID" disabled /><input placeholder="Password" type="password" disabled /><button className="primary wide" disabled>Login</button></section></main>; }

function Compose({ user, onClose, onDone }: { user: User; onClose: () => void; onDone: () => void }) {
  const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [recipients, setRecipients] = useState<string[]>([]); const [fileName, setFileName] = useState(''); const [attachment, setAttachment] = useState<File>(); const [start, setStart] = useState(''); const [delay, setDelay] = useState('2000'); const [limit, setLimit] = useState('200'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const formattedStart = start ? new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(start)) : 'Choose a date and time';
  const handleStartChange = (event: React.ChangeEvent<HTMLInputElement>) => setStart(event.target.value);
  const parseFile = (file: File) => { if (!/\.(csv|txt)$/i.test(file.name) || (file.type && !['text/csv', 'text/plain', 'application/vnd.ms-excel'].includes(file.type))) return setError('Lead list must be a CSV or TXT file.'); if (file.size > 5 * 1024 * 1024) return setError('Lead list must be smaller than 5 MB.'); setError(''); setFileName(file.name); const reader = new FileReader(); reader.onload = () => { const matches = String(reader.result).match(/[\w.+-]+@[\w-]+\.[\w.-]+/g) ?? []; setRecipients([...new Set(matches.map(x => x.toLowerCase()))]); }; reader.readAsText(file); };
  const parseAttachment = (file: File) => { if (file.size > 5 * 1024 * 1024) return setError('Attachments must be 5 MB or smaller.'); setError(''); setAttachment(file); };
  const submit = async () => { setError(''); if (!recipients.length) return setError('Upload a lead list with at least one email address.'); if (!subject.trim() || !body.trim()) return setError('Subject and message are required.'); if (!start || Number.isNaN(new Date(start).getTime())) return setError('Choose a valid future start time.'); setBusy(true); try { await api.schedule({ recipients, subject, body, startTime: new Date(start).toISOString(), delayBetweenMs: Number(delay) || 0, hourlyLimit: Number(limit) || 1, attachment }); onDone(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not schedule'); } finally { setBusy(false); } };
  return <div className="overlay"><section className="compose"><header><button className="icon-button" onClick={onClose}><ArrowLeft size={17}/></button><span>Compose New Email</span><div className="compose-actions"><label className="attach-button" title="Attach file"><Paperclip size={16}/><input type="file" onChange={e=>e.target.files?.[0] && parseAttachment(e.target.files[0])}/></label><Clock3 size={16}/><button className="outline" onClick={submit} disabled={busy}>{busy ? 'Scheduling...' : 'Send'}</button></div></header><div className="compose-form"><label>From <span className="sender-pill">{user.email} <ChevronDown size={12}/></span></label><label className="to-field">To <span className="recipient-chips">{recipients.length ? recipients.map(email => <span key={email}>{email}</span>) : <em>Upload a lead list to add recipients</em>}</span></label><label>Subject <input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/></label><div className="settings"><label><span>Delay between emails</span><span className="unit-input"><input value={delay} onChange={e=>setDelay(e.target.value)} type="text" inputMode="numeric" aria-label="Delay between emails in seconds"/><em>seconds</em></span></label><label><span>Hourly limit</span><span className="unit-input"><input value={limit} onChange={e=>setLimit(e.target.value)} type="text" inputMode="numeric" aria-label="Hourly email limit"/><em>emails/hour</em></span></label><label className="start-time-field"><span>Start time</span><span className="date-picker"><strong>{formattedStart}</strong><input value={start} onChange={handleStartChange} type="datetime-local" aria-label="Start date and time"/><span className="date-picker-button" aria-hidden="true"><CalendarClock size={16}/></span></span></label></div><div className="upload-row"><label className="upload"><FileUp size={14}/> {fileName || 'Upload Lead List'}<input type="file" accept=".csv,.txt" onChange={e=>e.target.files?.[0] && parseFile(e.target.files[0])}/></label>{recipients.length > 0 && <span className="count"><Check size={14}/> {recipients.length} emails</span>}</div>{attachment && <div className="attachment-row"><Paperclip size={16}/><span><strong>{attachment.name}</strong><em>{(attachment.size / 1024 / 1024).toFixed(2)} MB attached</em></span><button type="button" onClick={()=>setAttachment(undefined)} aria-label="Remove attachment"><X size={15}/></button></div>}<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Type Your Reply..."></textarea>{error && <p className="error">{error}</p>}</div></section></div>;
}

function Table({ emails, sent }: { emails: Email[]; sent: boolean }) { if (!emails.length) return <div className="empty"><Mail size={23}/><h3>No {sent ? 'sent' : 'scheduled'} emails yet</h3><p>{sent ? 'Emails you send will appear here.' : 'Schedule your first email campaign to see it here.'}</p></div>; return <div className="email-list">{emails.map(email => <article className="email-row" key={email.id}><div className="recipient"><span className="avatar small">{initials(email.recipient)}</span><div><strong>{email.recipient}</strong><span>{sent ? 'Sent' : 'To'} · {email.subject}</span></div></div><div className="time">{sent ? formatDate(email.sent_at ?? email.scheduled_at) : formatDate(email.scheduled_at)}</div><span className={`status ${email.status}`}><i></i>{email.status}</span><Star size={17} className="star"/></article>)}</div>; }

function Dashboard({ user }: { user: User }) { const [tab, setTab] = useState<'scheduled'|'sent'>('scheduled'); const [emails, setEmails] = useState<Email[]>([]); const [counts, setCounts] = useState({ scheduled: 0, sent: 0 }); const [loading, setLoading] = useState(true); const [compose, setCompose] = useState(false); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [filterOpen, setFilterOpen] = useState(false); const [dateFilter, setDateFilter] = useState<'all'|'today'|'week'>('all');
  const load = () => { setLoading(true); setError(''); Promise.all([api.emails(tab), api.counts()]).then(([items, totals]) => { setEmails(items); setCounts(totals); }).catch(e=>setError(e.message)).finally(()=>setLoading(false)); }; useEffect(load, [tab]);
  const visibleEmails = emails.filter(email => { const query = search.trim().toLowerCase(); const matchesSearch = !query || email.recipient.toLowerCase().includes(query) || email.subject.toLowerCase().includes(query); const date = new Date(email.sent_at ?? email.scheduled_at); const now = new Date(); const matchesDate = dateFilter === 'all' || (dateFilter === 'today' ? date.toDateString() === now.toDateString() : date.getTime() <= now.getTime() + 7 * 86400000); return matchesSearch && matchesDate; });
  return <div className="app-shell"><div className="window-bar">Homepage</div><aside><div className="brand-mark">ONB</div><div className="account"><Avatar user={user}/><div><strong>{user.name}</strong><span>{user.email}</span></div><ChevronDown size={15}/></div><button className="compose-button" onClick={()=>setCompose(true)}><Plus size={16}/> Compose</button><small>CORE</small><button className={`nav ${tab==='scheduled'?'active':''}`} onClick={()=>setTab('scheduled')}><CalendarClock size={17}/> Scheduled <b>{counts.scheduled}</b></button><button className={`nav ${tab==='sent'?'active':''}`} onClick={()=>setTab('sent')}><Send size={17}/> Sent <b>{counts.sent}</b></button><div className="sidebar-bottom"><button className="nav" onClick={async()=>{await api.logout(); location.reload()}}><LogOut size={17}/> Logout</button></div></aside><main className="mailbox"><header className="topbar"><div className="search"><Search size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search"/></div><div className="filter-wrap"><button className={`toolbar-button ${filterOpen?'active':''}`} onClick={()=>setFilterOpen(value=>!value)} aria-label="Filter emails"><Filter size={16}/></button>{filterOpen && <div className="filter-menu"><strong>Filter by date</strong><button className={dateFilter==='all'?'selected':''} onClick={()=>{setDateFilter('all');setFilterOpen(false)}}>All emails</button><button className={dateFilter==='today'?'selected':''} onClick={()=>{setDateFilter('today');setFilterOpen(false)}}>Today</button><button className={dateFilter==='week'?'selected':''} onClick={()=>{setDateFilter('week');setFilterOpen(false)}}>Next 7 days</button></div>}</div><button className="toolbar-button" onClick={load} aria-label="Refresh emails"><RefreshCw size={16}/></button></header>{error && <p className="error inline">{error}</p>}{loading ? <div className="loading"><span></span>Loading emails...</div> : <Table emails={visibleEmails} sent={tab==='sent'}/>}</main>{compose && <Compose user={user} onClose={()=>setCompose(false)} onDone={()=>{setCompose(false); setTab('scheduled'); load()}}/>}</div>; }
function App() { const [user, setUser] = useState<User|null>(null); const [loading, setLoading] = useState(true); useEffect(()=>{api.me().then(setUser).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]); if (loading) return <div className="loading full"><span></span>Loading Outbox...</div>; return user ? <Dashboard user={user}/> : <Login/>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
